### PR TITLE
 #162949061 Upgrade from Django 1.1 to 2.1

### PR DESCRIPTION
**Pull request by sharkdevs**
# What does the PR do?
Upgrade the project Django version from 1.1 to 2.1.4

# Description of the Task to be Completed?
- Upgrade Django version
- Change URL resolvers
- Change URL resolvers to use path

# How should this be manually tested?
- Clone the repository 
  ` git clone https://github.com/andela/ah-robotics.git`
- Create a virtual environment in the ah-robotics folder:
   `virtualenv your_virtual_environment`
- Activate the virtual environment created:
  `source your_virtual_environment/bin/activate`
- Install dependencies from the requirements file:
  `pip install -r requirements.txt`
- Switch to `ch-upgrade-django-162949061` branch
  `git checkout ch-upgrade-django-162949061`
- Open the python terminal and type ` python3 -m django --version` to check the version

# Relevant Pivotal Tracker Stories?
 [#162949061](https://www.pivotaltracker.com/n/projects/2235171/stories/162949061)

# Screenshots?
screen shot 2019-01-10 at 13 07 46

### CODE REVIEW

**Comment by jomasim** [comment]
Everything looks fine you are good to go
Just punctuate the first heading properly by adding a question mark at the end 
 "What does the PR do?"

**Comment by Teatoller** [comment]
Dear Sharkdev,
I have followed the instruction provided but not been successful to get the result of the django version.
```
Clone the repository
git clone https://github.com/andela/ah-robotics.git
Switch to ch-upgrade-django-162949061 branch
Open the python terminal and type python3 -m django --version to check the version
```
I have provided the screenshot below.
#### The screenshot
screenshot 2019-01-10 at 14 19 22

To improve the quality of the PR I would like to bring to your attention the following syntax gaps.
1. ```What does the PR do``` add a **"?"** at the end of the title.
2. In the section ```Description of the Task to be Completed``` consider using CAPS for the first letter on the following lines.
```
- change URL resolvers
- change URL resolvers to use path
```
Let me know soonest you finalize on these few hints to enable me to carry out a complete review.

**Regards**
**Steven Ennis**

**Review by Paulvitalis200 — COMMENTED** [review]
Be sure to include instructions on hot to install requirements.txt file in the PR.

**Comment by sharkdevs** [comment]
> Dear Sharkdev,
> I have followed the instruction provided but not been successful to get the result of the django version.
> 
> ```
> Clone the repository
> git clone https://github.com/andela/ah-robotics.git
> Switch to ch-upgrade-django-162949061 branch
> Open the python terminal and type python3 -m django --version to check the version
> ```
> I have provided the screenshot below.
> 
> #### The screenshot
> screenshot 2019-01-10 at 14 19 22
> 
> To improve the quality of the PR I would like to bring to your attention the following syntax gaps.
> 
> 1. `What does the PR do` add a **"?"** at the end of the title.
> 2. In the section `Description of the Task to be Completed` consider using CAPS for the first letter on the following lines.
> 
> ```
> - change URL resolvers
> - change URL resolvers to use path
> ```
> Let me know soonest you finalize on these few hints to enable me to carry out a complete review.
> 
> **Regards**
> **Steven Ennis**

Thank you. Let me add more instructions pertaining to Virtual environment setup.

**Review by waracci — COMMENTED** [review]
Looks good to me, only to reiterate on what the other team members have mentioned, make sure the installation instructions are clear.

**Comment by sharkdevs** [comment]
@Teatoller, Changes done as requested above.

**Pull request merged**
