### PR TITLE
#162949071 Write out descriptive validation error messages

### PR DESCRIPTION
**Pull request by Paulvitalis200**
#### What does this PR do?
Enables users to receive descriptive validation error messages

#### Description of Task to be completed?
Write out descriptive error messages in the views.py file

#### How should this be manually tested?
1. Clone this repository on your local machine using `git clone https://github.com/andela/ah-robotics.git`
2. Change your working directory to the project's directory using `cd ah-robotics`
3. Change to the specific branch `ft-signup-validation-messages-162949071` using `git checkout ft-signup-validation-messages-162949071`
4. Create a virtual environment using the following command: `python3 -m virtualenv env`
5. Activate the virtual environment using `source env/bin/activate`
6. Install all the requirements using `pip install -r requirements.txt`

### Database setup

Ensure [PostgreSQL](https://www.postgresql.org/) is installed and is running psql, follow these steps to create a new user and a database which will be used in the application.

  1. Start the postgres database server using the command:
  
      `pg_ctl -D /usr/local/var/postgres start`

  2. Run psql interactive terminal

      `psql postgres`

  3. Create a new user:

      `CREATE USER sample_username WITH PASSWORD 'sample_password';`

  4. Grant privileges to the user:

      `ALTER USER sample_username CREATEDB;`

  5. Create a database:

      `CREATE DATABASE sample_database_name WITH OWNER sample_username;`

  6. Exit psql interactive with the following command: `\q`

  7. Create a **.env** file and add the following configuration variables

      ```source-json
      source env/bin/activate
      export DB_NAME="database_name"
      export DB_USER="sample_username"
      export DB_PASS="sample_password"
      export DB_HOST="host_name_eg_localhost"
      export DB_PORT="port_number_eg_5432"
      ```

  7. Source .env to set the configuration variables in the terminal:

      `source .env`
  8. Run migrations through the terminal to create the tables in the database:
      (i) Make the migrations using: `python manage.py makemigrations`.
      (ii) Apply the migrations using: `python manage.py migrate`
      
### Testing the feature

1. Run the server from the terminal using `python manage.py runserver`.
2. Download [Postman](https://www.getpostman.com/) and after it is installed, open it on your local machine and Paste the URL `http://127.0.0.1:8000/api/v1/users/` to test.
3. On the body section on postman select _raw_ and type as _JSON/application_.
4. Add your payload to the **body** section using the following format:

```
    {
        "user": {
            "username": "sample_username",
            "email": "sample_email",
            "password": "sample_password"
            }
    }
```

4. Once all the fields are inserted, click **POST**.

### Running tests
1. Go to the terminal and ensure that the server is not running.
2. Run the tests by typing in the following command: `python manage.py test`

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#162949071](https://www.pivotaltracker.com/n/projects/2235171/stories/162949071)
#### Screenshots (if appropriate)
Successful sign up

#
screen shot 2019-01-16 at 20 22 46

Error message when user with the email and username already exist
screen shot 2019-01-16 at 20 13 51

Error message when password does not meet the required criteria
screen shot 2019-01-16 at 20 24 04

Error message when a particular field is missing
screen shot 2019-01-16 at 20 25 07

Error message when an invalid username is used

#
screen shot 2019-01-16 at 20 26 30

## Questions:
Questions are welcome

### CODE REVIEW

**Comment by jomasim** [comment]
@Paulstar200  and @sharkdevs  
- Give instructions on setting environment variables on  .env file
- Give more instructions on how testing should be done with postman
- Instructions on setting database and running the migrations

**Comment by Paulvitalis200** [comment]
> @Paulstar200 and @sharkdevs
> 
> * Give instructions on setting environment variables on  .env file
> * Give more instructions on testing should be done with postman
> * Instructions on setting database and running the migrations

Thank you for your feedback Joma. I have updated the PR. You can have a look again and test it.

**Comment by jomasim** [comment]
> > @Paulstar200 and @sharkdevs
> > 
> > * Give instructions on setting environment variables on  .env file
> > * Give more instructions on testing should be done with postman
> > * Instructions on setting database and running the migrations
> 
> Thank you for your feedback Joma. I have updated the PR. You can have a look again and test it.

@Paulstar200  and @sharkdevs  Good work people
you only need to add a few instructions on testing your feature with postman
- on the body section on postman select raw and type as JSON/application
- add your payload to the body section

**Comment by Paulvitalis200** [comment]
> > > @Paulstar200 and @sharkdevs
> > > 
> > > * Give instructions on setting environment variables on  .env file
> > > * Give more instructions on testing should be done with postman
> > > * Instructions on setting database and running the migrations
> > 
> > 
> > Thank you for your feedback Joma. I have updated the PR. You can have a look again and test it.
> 
> @Paulstar200 and @sharkdevs Good work people
> you only need to add a few instructions on testing your feature with postman
> 
> * on the body section on postman select raw and type as JSON/application
> * add your payload to the body section

Thank you for the feedback @jomasim. I am editing the Pull request with those instructions.

**Review by johnwayodi — COMMENTED** [review]
Good work, tested and working.

>### Running tests
>1. Use `python manage.py test`

However you might want to provide more color to this instruction. i.e 
1. Head back to terminal and run the command `python manage.py test`

**Comment by Teatoller** [comment]
Dear Paul/Meshack,

I am able to follow your instructions upto point 8. However when I try to execute point 9 on the migrations it fails.

See screenshot.

screenshot 2019-01-16 at 15 19 11

Kindly include the branch to be tested to correct this anomaly.

Regards
Steven Ennis

**Comment by Paulvitalis200** [comment]
> Good work, tested and working.
> 
> > ### Running tests
> > 
> > 1. Use `python manage.py test`
> 
> However you might want to provide more color to this instruction. i.e
> 
> 1. Head back to terminal and run the command `python manage.py test`

Thank you for your feedback @johnwayodi . I have updated the PR with the change.

**Comment by sharkdevs** [comment]
> Dear Paul/Meshack,
> 
> I am able to follow your instructions upto point 8. However when I try to execute point 9 on the migrations it fails.
> 
> See screenshot.
> 
> screenshot 2019-01-16 at 15 19 11
> 
> Kindly include the branch to be tested to correct this anomaly.
> 
> Regards
> Steven Ennis

Thanks, being fixed

Great!, with the adjustments you have made I have been able to get to the next point.

screenshot 2019-01-16 at 15 29 53

I would suggest at the *```Running tests```* just before the ```python manage.py test``` may you include the instruction ```control + C``` to free the terminal for the next command. 

With that in place we have a happy user. **Nice job!**
screenshot 2019-01-16 at 15 40 37

Regards
Steven Ennis

**Review by waracci — COMMENTED** [review]
In connection with our [PTR9](https://github.com/andela/ah-robotics/pull/9), I think we should sync the tests setUp and test files structure. Since tests will be used throughout the development lifetime of the application, its something we should get it right the first time.

Ps: Am saying this because I observed that the tests for both PRs are set up differently, this must have been the reason why one person was to be assigned the task of writing all the tests.

**Comment by Paulvitalis200** [comment]
Hey @waracci ,
I agree. I think we can go with one format for the file structure. Once the other branch is merged, we can update our file structure to match it.

**Comment by Collins33** [comment]
Update the screenshots. They currently instruct using a url that returns a 404

**Comment by Paulvitalis200** [comment]
> Update the screenshots. They currently instruct using a url that returns a 404

Hey @Collins33 ,
Thank you for the feedback. I have updated the screenshots

**Comment by sharkdevs** [comment]
> Update the screenshots. They currently instruct using a url that returns a 404

@Collins33 the screenshots are duly updated. Thank you.

**Pull request merged**
