### PR TITLE
#163259618 Add code climate to backend repo

### PR DESCRIPTION
**Pull request by jomasim**
#### What does this PR do?
- Add code climate to backend repo

#### Description of Task to be completed?
- Integrate backend repo with code climate
- Update README.md with code climate badge

#### How should this be manually tested?
Use the link [code-climate-badge](https://github.com/andela/ah-robotics/tree/ch-code-climate-integration-163259618) to check code climate badge on Github or use the steps below to view the same on your local machine : 

1. Open terminal and clone the repo:

    `git clone https://github.com/andela/ah-robotics.git`

2. Change directory into the cloned repository.

    `cd ah-robotics`

3. Checkout to the chore branch

    ```
      git checkout ch-code-climate-integration-163259618
   ```
4. Open Readme.md file in preview mode
#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#163259618](https://www.pivotaltracker.com/n/projects/2235171/stories/163259618)

#### Screenshots (if appropriate)
Readme code climate badge on Github
screenshot 2019-01-17 at 09 20 35

README.md preview mode
screenshot 2019-01-17 at 08 08 51

### CODE REVIEW

**Comment by Teatoller** [comment]
Hello @jomasim

Kindly verify if the branch details are accurate.
It is throwing an error.

screenshot 2019-01-17 at 08 47 54


Regards
Steven Ennis

**Comment by jomasim** [comment]
> Hello @jomasim
> 
> Kindly verify if the branch details are accurate.
> It is throwing an error.
> 
> screenshot 2019-01-17 at 08 47 54
> 
> Regards
> Steven Ennis

@Teatoller I have updated the chore branch name kindly check and confirm again whether it is ok.

Thank you, Joma your response is prompt. 

May you add this screenshot.
Ask the user to click on the windows on the top right-hand corner of the pane to access the preview mode if on Vscode.

screenshot 2019-01-17 at 08 59 01

I have otherwise managed to view the maintainability badge with a "B" score.
Good stuff.

Regards
Steven Ennis

**Review by johnwayodi — COMMENTED** [review]
>chore(integrate code-climate): Add code climate to backend repo

Nice work, now we can see the maintainability and work on improving it. 
A suggestion on the commit message, **chore(code-climate)** would have been better as you have indicated the integration aspect on the message body.

**Comment by johnwayodi** [comment]
And also check your PR title to ensure it conforms to the standards in the engineering playbook.

**Comment by waracci** [comment]
> And also check your PR title to ensure it conforms with the standards in the engineering playbook.

Yeah fix the PR title.

@waracci  Thanks for that observation I have fixed the PR title according to the engineering playbook standards.

**Review by waracci — COMMENTED** [review]
Looks good. The badge is visible and redirects to the Code climate report.

**Review by sharkdevs — COMMENTED** [review]
The feature is ok. however, do not capitalize the description of your commit message. Check the engineering playbook for more information

**Comment by jomasim** [comment]
> The feature is ok. however, do not capitalize the description of your commit message. Check the engineering playbook for more information

@sharkdevs Thanks for your feedback I have fixed the issues you can kindly check and confirm.

**Review by johnwayodi — APPROVED** [review]

**Review by Paulvitalis200 — APPROVED** [review]
Hey @jomasim,
This is good work. It is working as expected and the instructions were easy to follow.

Regards,
Paul Vitalis Otieno

**Comment by Collins33** [comment]
Awesome work on the implementation

**Pull request merged**
