### PR TITLE
#163447785 implement tests for login functionality

### PR DESCRIPTION
**Pull request by waracci**
#### What does this PR do?

Implement tests for the login feature

#### Description of Task to be completed

- Edit serializers.py file to include left out return statements
- Setup base test with login test variables and methods

### Getting Started

1. Open terminal and clone the repo:

    `git clone https://github.com/andela/ah-robotics.git`

2. Change directory into the cloned repository.

    `cd ah-robotics`

3. Checkout to the Chore branch

    `git checkout ch-test-login-163447785 `

4. Create a virtual environment by running the following commands:

    `virtualenv -p python3 env`

    or

    `python3 -m virtualenv env`

5. Once the virtual environment has been setup, activate it and install the packages required by the project,
    these are contained in the file named `requirements.txt`

      `source env/bin/activate`

      `pip install -r requirements.txt`

### setting up the database

> Ensure PostgreSQL is installed and is running psql, follow these steps to create a new user and a database which will be used in the application.

  1. Start the postgres database server using the command:
  
      `pg_ctl -D /usr/local/var/postgres start`

  2. Run psql interactive terminal

      `psql postgres`

  3. Create a new user:

      `CREATE USER sample_username WITH PASSWORD 'sample_password';`

  4. Grant privileges to the user:

      `ALTER USER sample_username CREATEDB;`

  5. Create a database:

      `CREATE DATABASE sample_database_name WITH OWNER sample_username;`

> Exit psql interactive with the command '\q'

  6. Create a .env as guided by the .env_example and add the following configuration variables

      ```source-json
      source env/bin/activate
      export DB_NAME="database_name"
      export DB_USER="sample_username"
      export DB_PASS="sample_password"
      export DB_HOST="host_name_eg_localhost"
      export DB_PORT="port_number_eg_5432"
      export TIME_DELTA="30"
      export EMAIL_HOST="smtp.gmail.com"
      ```
      > Refer to the email pinned on the Team Slack channel
      ```
      export EMAIL_HOST_USER="user@example.com"
      export EMAIL_HOST_PASSWORD="email_password"
      ```
      > The rest of the environment variables are to remain as indicated
      ```
      export EMAIL_PORT=587
      export PASSWORD_RESET_URL="api/v1/reset_password"
      export CLIENT_DOMAIN="127.0.0.1:8000"
      ```
  7. Source .env to set the configuration variables:

      `source .env`
  8. Run migrations to create the tables in the database:

      ```source-json
      python manage.py makemigrations
      python manage.py migrate
      ```

---
### Collect static files

Run the following command to collect static files.

`python manage.py collectstatic`

### Run The Server

Once everything has been setup, to run the application run the command:

   `python manage.py runserver`

The application can be accessed in the url <http://localhost:8000>

---

### Runnning the tests

1. On the terminal run the following command to execute the tests.

`python manage.py test`

2. To get the coverage of the tests locally, run:

`coverage run --source=authors/ manage.py test && coverage report`

> If you do not have coverage installed, install it with the following command

`pip install coverage`

#### The relevant pivotal tracker stories.

[#163447785](https://www.pivotaltracker.com/story/show/163447785)

#### Screenshots

1. Running the tests.

screenshot 2019-01-24 at 14 33 59

2. Running the tests to get the coverage.

screenshot 2019-01-24 at 14 32 28

### CODE REVIEW

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @waracci ,
Good work the tests work as expected. However, I would like to point out that you need to state in your Pull Request how we should get out of the postgres command shell.

**Review by sharkdevs — COMMENTED** [review]
Amend your commit message to rectify the following spellings error in the commit body: `Refator password serializers` to `Refactor`.

**Comment by waracci** [comment]
> Hey @waracci ,
> Good work the tests work as expected. However, I would like to point out that you need to state in your Pull Request how we should get out of the postgres command shell.

well noted working on it, asap.

**Comment by waracci** [comment]
> Amend your commit message to rectify the following spellings error in the commit body: `Refator password serializers` to `Refactor`.

well noted working on it, asap.

**Review by johnwayodi — COMMENTED** [review]
Followed the instructions, all tests are passing as expected.

**Comment by jomasim** [comment]
@waracci  I have managed to run the tests and I didn't find any errors when setting up otherwise good work.

**Comment by Collins33** [comment]
The tests are running well. Good work.

**Pull request merged**
