### PR TITLE
#162949065 Integrate Travis to Coveralls Test Coverage

### PR DESCRIPTION
**Pull request by johnwayodi**
#### What does this PR do?
Integrate test coverage with Travis build result. 

#### Description of Task to be completed?
Install coveralls
Update the .travis.yml file with the  necessary configurations.

#### How should this be manually tested?
1. Open the project repository on GitHub here : [ah-robotics](https://github.com/andela/ah-robotics)
3. Switch to branch `ch-travis-integration-162949065`
4. Scroll down to the _**README**_ section
5. Click on the **_coverage_** badge to see the test coverage info on the coveralls.io website.
#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#162949065](https://www.pivotaltracker.com/story/show/162949065)

#### Screenshot
**Coverage report on coveralls**
screen shot 2019-01-10 at 12 10 14 am

#### Questions:
Feel free to give feedback and raise any questions.

### CODE REVIEW

**Review by waracci — COMMENTED** [review]
Great, I see it works and passes the `Travis build`.
Why did you include two PT stories? One would have just been enough.

**Comment by johnwayodi** [comment]
> Why did you include two PT stories? One would have just been enough.

I initially thought both stories were in some way involved, let me change that to the most relevant one.
Thanks for the suggestion.

**Comment by sharkdevs** [comment]
Travis is passing though the coveralls badge is not yet updated. still unknown. @Paulstar200 you can check that.

**Comment by johnwayodi** [comment]
> Travis is passing though the coveralls badge is not yet updated. still unknown. @Paulstar200 you can check that.

@sharkdevs , the coverage badge will automatically update once the branch is merged to develop.

**Review by sharkdevs — COMMENTED** [review]
@johnwayodi That's fine. The set up is ok

**Review by Paulvitalis200 — APPROVED** [review]
Good work

**Pull request merged**
