### PR TITLE
#162949068 Integrate Coveralls Code coverage service

### PR DESCRIPTION
**Pull request by Paulvitalis200**
#### What does this PR do?
Integrates Coveralls code coverage badge with the repository

#### Description of Task to be completed?
Update the README.md with the coverage badge.
Integrate this repository with [coveralls.io](coveralls.io)

#### How should this be manually tested?
Go to [github](github.com)
Open the project repository called [ah-robotics](url)
Go to the branch `ch-coveralls-coverage-integration-162949068`
Scroll down to the **README** section
Click on the [coverage](https://coveralls.io/github/andela/ah-robotics?branch=develop) link
#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#162949068](https://www.pivotaltracker.com/n/projects/2235171/stories/162949068)

#### Screenshots (if appropriate)
image

#### Questions:
Feel free to give feedback and raise any questions.

### CODE REVIEW

**Review by johnwayodi — APPROVED** [review]
Everything looks good.

**Comment by johnwayodi** [comment]
> What are the relevant pivotal tracker stories?
   #162949068

The _story id_ **#162949068** should be a link that redirects to the PT Board story, kindly address that @Paulstar200.

**Comment by waracci** [comment]
The Coveralls badge indicates that the coverage is unknown, what could be the problem?

**Comment by jomasim** [comment]
I think it will reflect the coverage once it is merged with the develop branch(default branch on the repo) @waracci

**Comment by Paulvitalis200** [comment]
@johnwayodi let me link the story Id to the pivotal tracker story. Thank you.

**Comment by Paulvitalis200** [comment]
@waracci I think after we merge it to develop and the Travis CI build is set up we will be able to see the coverage.

**Comment by Teatoller** [comment]
Hello Paulstar,
It is wonderful that you the coveralls badge linked.
I have seen the concern raised about the "coverage unknown" it is a little unsettling in that aspect for now.
I would recommend you have on your PR, _**a step-by-step guide**_ to enable a reviewer or user **clone the repository** and actually test it on their machine. 
The style you have used is high level but fails to fulfill the instructions that were given during the kick-off.

*Regards*
*Steven Ennis*

**Comment by Paulvitalis200** [comment]
Hey Steven,
Thank you for your feedback. I have realized that I failed to include the branch that one should check out to in order to run the tests and view the code coverage on their local machines. I will update my Pull Request to point out the steps that one should follow in order to clone the repository and l will liaise with @johnwayodi to get some tests as currently, we have no tests. The reason we have the coverage as unknown is that I believe we have no tests yet and the coverage badge currently points to the **develop** branch


Regards
Paul Vitalis

**Pull request merged**
