### PR TITLE
#162949073 User password reset via email

### PR DESCRIPTION
**Pull request by waracci**
### Getting Started

1. Open terminal and clone the repo:

    `git clone https://github.com/andela/ah-robotics.git`

2. Change directory into the cloned repository.

    `cd ah-robotics`

3. Checkout to the Feature branch

    `git checkout ft-password-reset-162949073`

4. Create a virtual environment by running the following commands:

    `virtualenv -p python3 env`

    or

    `python3 -m virtualenv env`

5. Once the virtual environment has been setup, activate it and install the packages required by the project,
    these are contained in the file named `requirements.txt`

      `source env/bin/activate`

      `pip install -r requirements.txt`

### setting up the database

> Ensure PostgreSQL is installed and is running psql, follow these steps to create a new user and a database which will be used in the application.

  1. Start the postgres database server using the command:
  
      `pg_ctl -D /usr/local/var/postgres start`

  2. Run psql interactive terminal

      `psql postgres`

  3. Create a new user:

      `CREATE USER sample_username WITH PASSWORD 'sample_password';`

  4. Grant privileges to the user:

      `ALTER USER sample_username CREATEDB;`

  5. Create a database:

      `CREATE DATABASE sample_database_name WITH OWNER sample_username;`
  6. Create a .env as guided by the .env_example and add the following configuration variables

      ```source-json
      source env/bin/activate
      export DB_NAME="database_name"
      export DB_USER="sample_username"
      export DB_PASS="sample_password"
      export DB_HOST="host_name_eg_localhost"
      export DB_PORT="port_number_eg_5432"
      export TIME_DELTA="30"
      export EMAIL_HOST="smtp.gmail.com"
      ```
      > Refer to the email pinned on the Team Slack channel
      ```
      export EMAIL_HOST_USER="user@example.com"
      export EMAIL_HOST_PASSWORD="email_password"
      ```
      > The rest of the environment variables are to remain as indicated
      ```
      export EMAIL_PORT=587
      export PASSWORD_RESET_URL="api/v1/reset_password"
      export CLIENT_DOMAIN="127.0.0.1:8000"
      ```
  7. Source .env to set the configuration variables:

      `source .env`
  8. Run migrations to create the tables in the database:

      ```source-json
      python manage.py makemigrations
      python manage.py migrate
      ```

---
### Collect static files

Run the following command to collect static files.

`python manage.py collectstatic`

### Run The Server

Once everything has been setup, to run the application run the command:

   `python manage.py runserver`

The application can be accessed in the url <http://localhost:8000>

---

### Testing the feature

1. Run the server from the terminal using python manage.py runserver.

2. Download [Postman](https://www.getpostman.com/) and after it is installed, open it on your local machine and Paste the URL <http://127.0.0.1:8000/api/v1/users/> to register a user.
3. On the body section on postman select `raw` and type as `JSON/application`.
Add your payload to the body section using the following format `but NOT with the exact credentials`:

> Kindly use a genuine email you have access to because an email will be sent, do NOT use a real password.

   
        {
        "user": {
            "username": "dojo1234",
            "email": "user@example.com",
            "password": "test1234#"
            }
          }
     
4. Once all the fields are inserted, click POST to register the user successfully.
5. Send another request to the endpoint: <http://127.0.0.1:8000/api/v1/account/forgot_password/> 
6. On the body section on postman select `raw` and type as `JSON/application`.
7. Add a payload of the following format, but with the email you registered with.
   ```
        {
        "email": "user@example.com"
         }
    ```
8. Send the Request and you should get the following message.
   ```
       {
            "message": "Kindly use the link sent to your email to reset your password"
       }
   ```
9. Open your email and you should have received an email with link to reset the password.
10. Click the link and the browser will open the `Django` interactive interface where you will change your password.
 
### Running tests
1. Go to the terminal and ensure that the server is not running.
2. Run the tests by typing in the following command: `python manage.py test`

### What are the relevant pivotal tracker stories?
[#162949073](https://www.pivotaltracker.com/story/show/162949073)

Screenshots:

1. Postman request

screenshot 2019-01-22 at 14 28 50

---

2. Email Template in inbox

screenshot 2019-01-22 at 14 24 53

---

3. Django interface to change password

screenshot 2019-01-22 at 14 29 37

---

4. Successful password update

screenshot 2019-01-22 at 14 30 26

5. Tests running on the terminal

screenshot 2019-01-22 at 17 54 08

### CODE REVIEW

**Review by sharkdevs — COMMENTED** [review]
There should be one blank line after the commit message header

**Review by sharkdevs — CHANGES_REQUESTED** [review]
All your commit messages should have a header, body, and footer as in the engineering playbook. Edit them.

**Review by johnwayodi — COMMENTED** [review]
Nice work, tested with my email and managed to perform the password reset.

**Comment by Teatoller** [comment]
Hello Warachi,
The updates you have made to the pull requests makes it possible to replicate the expected outcomes.
Thank you.

**Comment by waracci** [comment]
> Hello Warachi,
> The updates you have made to the pull requests makes it possible to replicate the expected outcomes.
> Thank you.

Thanks for your keen review and feedback.

**Comment by waracci** [comment]
> Nice work, tested with my email and managed to perform the password reset.

Thanks for your keen review and feedback.

**Comment by waracci** [comment]
> All your commit messages should have a header, body, and footer as in the engineering playbook. Edit them.

Well noted, thanks for the correction @sharkdevs.

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @waracci and @jomasim ,
Good work on the pull request. I  followed all the steps and managed to reset my password.

**Review by Paulvitalis200 — COMMENTED** [review]
However, ensure that the email styling matches the screenshots. The Email I got did not match the screenshots. Check my screenshot below.
image

**Review by sharkdevs — APPROVED** [review]

**Comment by Collins33** [comment]
Awesome work on the implementation.

**Pull request merged**
