### PR TITLE
#163092870 update readme to include steps of setting up the application

### PR DESCRIPTION
**Pull request by waracci**
#### What does this PR do?

Update the readme file

#### Description of Task to be completed?

> Update the `README.md`

- Update the file to include cloning the repository
- Include instructions for setting up and running the database
- Include instructions to run tests

#### How should this be manually tested?

1. Open terminal and clone the repo:

    `git clone https://github.com/andela/ah-robotics.git`

2. Change directory into the cloned repository.

    `cd ah-robotics`

3. Checkout to the Chore branch

    `git checkout ch-update-readme-163092870`

4. Create a virtual environment inside the cloned project by running the following commands:

    `cd ah-robotics`

    `virtualenv -p python3 env`

    or

    `python3 -m virtualenv env`

5. Once the virtual environment has been set up, activate it and install the packages required by the project,
    these are contained in the file named `requirements.txt`

      `source env/bin/activate`

      `pip install -r requirements.txt`

### setting up the database

> Ensure PostgreSQL is installed and is running psql, follow these steps to create a new user and a database which will be used in the application.

  1. Start the postgres database server using the command:
  
      `pg_ctl -D /usr/local/var/postgres start`

  2. Run psql interactive terminal

      `psql postgres`

  3. Create a new user:

      `CREATE USER sample_username WITH PASSWORD 'sample_password';`

  4. Grant privileges to the user:

      `ALTER USER sample_username CREATEDB;`

  5. Create a database:

      `CREATE DATABASE sample_database_name WITH OWNER sample_username;`
  6. Create a .env as guided by the .env_example and add the following configuration variables

      ```source-json
      export DB_NAME="database_name"
      export DB_USER="sample_username"
      export DB_PASS="sample_password"
      export DB_HOST="host_name_eg_localhost"
      export DB_PORT="port_number_eg_5432"
      ```

  7. Source .env to set the configuration variables:

      `source .env`
  8. Run migrations to create the tables in the database:

      ```source-json
      python manage.py makemigrations
      python manage.py migrate
      ```

---

### Run The Server

Once everything has been setup, to run the application run the command:

   `python manage.py runserver`

The application can be accessed in the url **http://localhost:8000**

---
#### What are the relevant pivotal tracker stories?

[#163092870](https://www.pivotaltracker.com/story/show/163092870)

#### Screenshots (if appropriate)
screenshot 2019-01-14 at 18 34 51

### CODE REVIEW

**Review by johnwayodi — COMMENTED** [review]
There seems to be a formatting issue in the section **setting up the database**, kindly look into it.

**Comment by waracci** [comment]
> There seems to be a formatting issue in the section **setting up the database**, kindly look into it.

Let me look into it, asap. Thanks!

**Review by sharkdevs — COMMENTED** [review]
`pip install -r requirenemts.txt` generates the error below. Correct spelling errors.
screen shot 2019-01-14 at 15 22 55

**Comment by waracci** [comment]
> `pip install -r requirements.txt` generates the error below. Include the instructions to checkout to the directory where requirements.txt is located before running the command.
> screen shot 2019-01-14 at 15 22 55

I do not know why this could be happening, any ideas?

**Comment by sharkdevs** [comment]
> > `pip install -r requirements.txt` generates the error below. Include the instructions to checkout to the directory where requirements.txt is located before running the command.
> > screen shot 2019-01-14 at 15 22 55
> 
> I do not know why this could be happening, any ideas?

resolved

> > `pip install -r requirements.txt` generates the error below. Include the instructions to checkout to the directory where requirements.txt is located before running the command.
> > screen shot 2019-01-14 at 15 22 55
> 
> I do not know why this could be happening, any ideas?

Yeah, change the command from  `pip install -r requirenemts.txt`
 to  `pip install -r requirements.txt`

**Comment by johnwayodi** [comment]
There are some formatting issues on the ReadMe file in the following sections. Look into them and correct them
screen shot 2019-01-14 at 3 50 18 pm
screen shot 2019-01-14 at 3 50 43 pm

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @waracci,
Please include in your steps how we should start the postgres server locally on our machines before we start creating the database and the user. You can use `pg_ctl -D /usr/local/var/postgres start`.

Thank you

**Comment by sharkdevs** [comment]
Also, include instructions to checkout to the branch where the changes are hosted.

**Comment by jomasim** [comment]
Check you commands for creating database and database user. You should first provide the command to login to postgres shell:
```
$ psql postgres 

```

screenshot 2019-01-14 at 15 50 05

**Comment by Paulvitalis200** [comment]
Hey @waracci ,
You can also export the environment variables by using `export` as follows:
`export DB_NAME="sample_dbname"`
`export DB_USER="sample_username"`
`export DB_PASS="samplepassword"`
`export DB_HOST="localhost"`
`export DB_PORT="5432"`

Regards, 
Paul Vitalis

**Comment by sharkdevs** [comment]
> Check you commands for creating database and database user. You should first provide the command to login to postgres shell:
> 
> ```
> $ psql postgres 
> ```

Is this necessary? Does one have to login to the Postgres shell to create the database?

**Comment by Teatoller** [comment]
Dear waracci,

I believe you have a great piece although you need to unlock a few areas to make the instructions work.

I have tried to create a virtual environment and was not able to do so. See the immediate screenshot.

screenshot 2019-01-14 at 15 35 37

#### virtual environment creation
I suggest you use this link to enhance your record for creating a virtual environment and possibly consider users who may be using **Windows** as well.
```https://packaging.python.org/guides/installing-using-pip-and-virtualenv/```
#### Installation of requirements .txt
The other challenge is a typo with the words _requirements_
 ```pip install -r requirenemts.txt```

#### This is causing an error as in the screenshot below;
screenshot 2019-01-14 at 15 40 15

**Comment by waracci** [comment]
> There are some formatting issues on the ReadMe file in the following sections. Look into them and correct them
> screen shot 2019-01-14 at 3 50 18 pm
> screen shot 2019-01-14 at 3 50 43 pm

Thanks for pointing it out! I am working on it.

**Comment by waracci** [comment]
> Dear waracci,
> 
> I believe you have a great piece although you need to unlock a few areas to make the instructions work.
> 
> I have tried to create a virtual environment and was not able to do so. See the immediate screenshot.
> 
> screenshot 2019-01-14 at 15 35 37
> 
> #### virtual environment creation
> I suggest you use this link to enhance your record for creating a virtual environment and possibly consider users who may be using **Windows** as well.
> `https://packaging.python.org/guides/installing-using-pip-and-virtualenv/`
> 
> #### Installation of requirements .txt
> The other challenge is a typo with the words _requirements_
> `pip install -r requirenemts.txt`
> 
> #### This is causing an error as in the screenshot below;
> screenshot 2019-01-14 at 15 40 15

Thanks for pointing this out, there is an error in the spelling of requirements. I am working on it.

**Comment by jomasim** [comment]
> > Check you commands for creating database and database user. You should first provide the command to login to postgres shell:
> > ```
> > $ psql postgres 
> > ```
> 
> Is this necessary? Does one have to login to the Postgres shell to create the database?

@sharkdevs  I ran into an error when trying to run the database commands:
screenshot 2019-01-14 at 15 27 58

**Comment by waracci** [comment]
I managed to implement all feedback received, kindly review it once again. Thanks!

**Review by johnwayodi — APPROVED** [review]
@waracci I followed the instructions and everything is okay, I also see you made changes to the ReadMe file.

**Review by Paulvitalis200 — APPROVED** [review]
Hey @waracci 
Thank you for implementing the feedback. It is running well at the moment.

Regards,
Paul Vitalis Otieno

**Comment by Collins33** [comment]
@waracci While following the instructions to setup up the application, the checking out should be done after a user enters the ah-robotics directory. Please look into this

**Comment by waracci** [comment]
> @waracci While following the instructions to setup up the application, the checking out should be done after a user enters the ah-robotics directory. Please look into this

Yes, well noted. Thanks.

**Comment by Collins33** [comment]
@waracci Good job on the implementation. This has really helped with setting up everything.

**Pull request merged**
